### ISSUE TITLE
Is there any plan for 1.15.2 or 1.16 updates?

### ISSUE THREAD

**Issue by rikka0w0** [MinecraftModDevelopment/AdditionalLootTables#17]
Is there any plan for 1.15.2 or 1.16 updates? I could help.

**Comment by jriwanek** [comment]
There is indeed, and your kind offer is most appreciated as we're very short handed.
Send a PR with your updates and we'll give you credit for assisting with the release!
Don't forget to join the MMD discord: https://discord.mcmoddev.com (permalink) to be able to interact, channel on the server btw is #alt-and-orespawn.

**Comment by dshadowwolf** [comment]
@rikka0w0: as far as @ALTPlugin goes it might be better to run with my other idea for this, which was to mirror JEI and use an IMC to register a handler that can be called to set things up in a similar manner. If you can get the port you are working on anywhere close to complete I might be able to find a few hours to rough in what I'm talking about.

**Comment by jriwanek** [comment]
Port merged, I'll work over the week to get it pushed to curseforge.
